version: '3'

services: 
  db:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    container_name: database
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "db"
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - mysql-compose-network
    
  redis:
    image: redis:4
    container_name: redis
    restart: always
    networks: 
      - mysql-compose-network
    ports: 
      - 6379:6379
    expose: 
      - 6379

  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge